#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        SERVICE_XPATH_NAME="ddclient"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_delete "${SERVICE_XPATH}"
        fi

        if [ -d /etc/ddclient ]; then
            rm -r /etc/ddclient
        fi

        if [ -d /var/cache/ddclient ]; then
            rm -r /var/cache/ddclient
        fi
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
